### PR TITLE
Gmt issue 72

### PR DESCRIPTION
**Pull request by vtnate**
Combined with [gmt pr #129](https://github.com/urbanopt/geojson-modelica-translator/pull/129), this addresses [gmt issue #72](https://github.com/urbanopt/geojson-modelica-translator/issues/72)

### CODE REVIEW

**Comment by nllong** [comment]
@vtnate  -- I merged down the GMT fixes and want to test this repo. Can you verify that these tests pass locally? You will have to do the following:

* In your MBL checkout, pull the latest changes (`git checkout issue1437_district_heating_cooling`, then `git pull`)
* Run `pip install -U --upgrade-strategy eager -r requirements.txt` in this repo
* Run `py.test`

My tests are failing with several items, for example `AssertionError: 8 != 11`

Thanks!

**Comment by vtnate** [comment]
@nllong Gah. Forgot to update that after the changes to the gj file. Fixed now.

**Comment by vtnate** [comment]
@nllong I used MBL branch `issue1437_1910_1stDHC` which worked. Branch `issue1437_district_heating_cooling` resulted in failure of test `test_spawn_two_buildings.py::SpawnTwoBuildingTest::test_to_modelica_defaults`.

**Comment by nllong** [comment]
hmm, that is strange. We need it to work with `issue1437_district_heating_cooling`. The problem is that `issue1437_district_heating_cooling` is a moving target. 

I just tested GMT (on develop) on `issue1437_district_heating_cooling` and the tests passed. I need to check the GMT-examples repo next.

**Comment by vtnate** [comment]
@nllong Line https://github.com/urbanopt/geojson-modelica-translator-examples/blob/gmt-issue-72/tests/test_spawn_two_buildings.py#L93 results in exitcode == 134 when I run with `issue1437_district_heating_cooling` branch. I haven't found that exit code in Docker, and I haven't been able to decipher the stdout.log file created in the output folder. There may be some clues in there, if it makes sense to you.

**Comment by vtnate** [comment]
All tests passed 🥳 🎉

**Pull request merged**
